config/routes.rb
RablExamples::Application.routes.draw do

  root :to => "cars#index"

  resources :cars

  match 'cars/car_check/:engine_size' => 'cars#car_check'
  match 'garage' => 'cars#garage'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/garage.rb
class Garage

  def name
    "My Garage"
  end

  def cars_in_stock
    Car.count
  end

  #dummy method to make the class "RABL" friendly
  def valid?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def car_check
    @cars = Car.where("engine_size > ?", Integer(params[:engine_size]))
    @message = "None found" unless @cars.present?
    flash[:notice] = "Flash notice message!!"

  end

  def garage
    @garage = Garage.new
  end

  # GET /cars
  # GET /cars.xml
  def index
    @cars = Car.all

#    respond_to do |format|
#      format.html # index.html.erb
#      format.xml  { render }
#      format.json  { render }
#    end
  end

  # GET /cars/1
  # GET /cars/1.xml
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.xml
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.xml
  def create
    #disable create for now
#    @car = Car.new(params[:car])
#
#    respond_to do |format|
#      if @car.save
#        format.html { redirect_to(@car, :notice => 'Car was successfully created.') }
#        format.xml  { render :xml => @car, :status => :created, :location => @car }
#      else
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @car.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # PUT /cars/1
  # PUT /cars/1.xml
  def update
    #disable update for now
#    @car = Car.find(params[:id])
#
#    respond_to do |format|
#      if @car.update_attributes(params[:car])
#        format.html { redirect_to(@car, :notice => 'Car was successfully updated.') }
#        format.xml  { head :ok }
#      else
#        format.html { render :action => "edit" }
#        format.xml  { render :xml => @car.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.xml
  def destroy
    #disable delete for now
#    @car = Car.find(params[:id])
#    @car.destroy
#
#    respond_to do |format|
#      format.html { redirect_to(cars_url) }
#      format.xml  { head :ok }
#    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/rabl_helper.rb
module RablHelper

  def node_if_present(name, &block)
#node(:message, :if => lambda { |m| @message.present? }) { @message }
    node(name, { :if => lambda { |m| m.send(name) } }, &block)
  end

end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :engine_size %><br />
    <%= f.text_field :engine_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Make</th>
    <th>Engine size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.name %></td>
    <td><%= car.make %></td>
    <td><%= car.engine_size %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @car.name %>
</p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>

<p>
  <b>Engine size:</b>
  <%= @car.engine_size %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RablExamples</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>